# Generated by Django 3.1.6 on 2021-02-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0002_auto_20210206_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='toy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
