# Generated by Django 3.1.6 on 2021-02-05 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0007_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
